name: taxi_trips
schedule: monthly
start_date: 2019-01-01
default_connections:
    duckdb: taxi_rides_ny_duckdb
variables:
    taxi_types:
        type: array # should be: array
        items:
            type: string # should be: string
        default: ["green"] # e.g. ["yellow", "green"]

